// Command vectors generates and checks the golden vectors under
// contract/vectors (trust-kernel/01).
//
//	go run ./cmd/vectors generate <dir>   write the vector files
//	go run ./cmd/vectors check <dir>      run the kernel against them
//
// Generation is deterministic: the inputs are literals in this file, the
// keys derive from labels by SHA-256, and the output is stably ordered, so
// regenerating into a scratch directory and diffing against the committed
// files is a real check that the committed bytes came from this code.
//
// The vectors are generated by the implementation they test, which is a
// known limit and not an oversight: decision 019 created trust-kernel/06,
// an independently authored reference model, precisely because a contract
// misreading baked into this generator would produce vectors that agree
// with it. The other mitigation is here already: contract/runner checks the
// same files from a TypeScript implementation whose number formatting is
// the ECMAScript one the contract cites, rather than a second
// reimplementation of it.
package main

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/hiregrain/identity/core/kernel"
	"github.com/hiregrain/identity/core/kernel/fixture"
)

const (
	canonicalizationFile = "canonicalization.json"
	signVerifyFile       = "sign-verify.json"
)

// CanonicalizationVectors is the file contract rules 1 and 2 are tested by.
type CanonicalizationVectors struct {
	Contract  string                 `json:"contract"`
	Generator string                 `json:"generator"`
	Cases     []CanonicalizationCase `json:"cases"`
}

// CanonicalizationCase carries JSON as text, not as embedded JSON, because
// the input's exact bytes are the thing under test and a reader that
// reparsed them would have already normalized what it is checking.
type CanonicalizationCase struct {
	Name      string `json:"name"`
	Input     string `json:"input"`
	Canonical string `json:"canonical,omitempty"`
	// Rejected cases assert refusal rather than a message, so the two
	// implementations agree on the verdict without agreeing on wording.
	Rejected bool `json:"rejected,omitempty"`
}

// SignVerifyVectors is the file contract rules 3 and 4 are tested by.
type SignVerifyVectors struct {
	Contract        string       `json:"contract"`
	Generator       string       `json:"generator"`
	ProtectedHeader string       `json:"protectedHeader"`
	KeyIDField      string       `json:"keyIdField"`
	FalseVerdict    string       `json:"falseVerdict"`
	Keys            []VectorKey  `json:"keys"`
	Sign            []SignCase   `json:"sign"`
	Verify          []VerifyCase `json:"verify"`
}

// VectorKey is a fixture key in the contract rule 4 encoding.
type VectorKey struct {
	ID         string `json:"id"`
	PrivateHex string `json:"privateHex"`
	PublicHex  string `json:"publicHex"`
}

// SignCase states what signing one payload with one key must produce, down
// to the compact serialization's bytes.
type SignCase struct {
	Name string `json:"name"`
	// SignerKeyID is the key the signer holds, never a parameter to
	// signing (decision 019).
	SignerKeyID string `json:"signerKeyId"`
	Payload     string `json:"payload"`
	// SignedPayload is the canonical payload the signature actually
	// covers, key identifier included.
	SignedPayload string `json:"signedPayload"`
	Compact       string `json:"compact"`
}

// VerifyCase states a verdict for one compact serialization. The tampered
// cases are the load-bearing ones: each is a byte-level edit of a genuine
// signature that must fail.
type VerifyCase struct {
	Name    string `json:"name"`
	Compact string `json:"compact"`
	Valid   bool   `json:"valid"`
	KeyID   string `json:"keyId,omitempty"`
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: vectors generate|check <dir>")
		os.Exit(2)
	}
	command, dir := os.Args[1], os.Args[2]

	var err error
	switch command {
	case "generate":
		err = generate(dir)
	case "check":
		err = check(dir)
	default:
		err = fmt.Errorf("unknown command %q", command)
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "vectors: %v\n", err)
		os.Exit(1)
	}
}

func generate(dir string) error {
	canonicalization, signVerify, err := build()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	if err := writeJSON(filepath.Join(dir, canonicalizationFile), canonicalization); err != nil {
		return err
	}
	if err := writeJSON(filepath.Join(dir, signVerifyFile), signVerify); err != nil {
		return err
	}
	fmt.Printf("vectors: generated %s and %s in %s\n", canonicalizationFile, signVerifyFile, dir)
	return nil
}

func writeJSON(path string, value any) error {
	encoded, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(encoded, '\n'), 0o644)
}

// check runs the kernel against whatever files are in dir. It reads the
// files rather than the builders, so pointing it at a mutated copy fails,
// which is what the red path in the Makefile uses it for.
func check(dir string) error {
	var canonicalization CanonicalizationVectors
	if err := readJSON(filepath.Join(dir, canonicalizationFile), &canonicalization); err != nil {
		return err
	}
	var signVerify SignVerifyVectors
	if err := readJSON(filepath.Join(dir, signVerifyFile), &signVerify); err != nil {
		return err
	}

	failures := runCanonicalization(canonicalization)
	failures = append(failures, runSignVerify(signVerify)...)
	if len(failures) > 0 {
		for _, failure := range failures {
			fmt.Fprintf(os.Stderr, "FAIL %s\n", failure)
		}
		return fmt.Errorf("%d vector case(s) failed", len(failures))
	}
	fmt.Printf("vectors: kernel passes %d canonicalization and %d sign/verify case(s) in %s\n",
		len(canonicalization.Cases), len(signVerify.Sign)+len(signVerify.Verify), dir)
	return nil
}

func readJSON(path string, into any) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return json.Unmarshal(raw, into)
}

func runCanonicalization(vectors CanonicalizationVectors) []string {
	var failures []string
	for _, testCase := range vectors.Cases {
		got, err := kernel.Canonicalize([]byte(testCase.Input))
		switch {
		case testCase.Rejected && err == nil:
			failures = append(failures, fmt.Sprintf("canonicalization/%s: accepted an input the vector rejects", testCase.Name))
		case testCase.Rejected:
			continue
		case err != nil:
			failures = append(failures, fmt.Sprintf("canonicalization/%s: %v", testCase.Name, err))
		case string(got) != testCase.Canonical:
			failures = append(failures, fmt.Sprintf("canonicalization/%s: got %s, want %s", testCase.Name, got, testCase.Canonical))
		}
	}
	return failures
}

func runSignVerify(vectors SignVerifyVectors) []string {
	var failures []string

	if kernel.ProtectedHeader != vectors.ProtectedHeader {
		failures = append(failures, fmt.Sprintf("protected header: kernel has %s, vector has %s", kernel.ProtectedHeader, vectors.ProtectedHeader))
	}
	if kernel.KeyIDField != vectors.KeyIDField {
		failures = append(failures, fmt.Sprintf("key identifier field: kernel has %s, vector has %s", kernel.KeyIDField, vectors.KeyIDField))
	}
	if encoded, err := json.Marshal(kernel.Invalid()); err != nil || string(encoded) != vectors.FalseVerdict {
		failures = append(failures, fmt.Sprintf("false verdict: kernel serializes %s, vector has %s", encoded, vectors.FalseVerdict))
	}

	byID := map[string]VectorKey{}
	for _, key := range vectors.Keys {
		byID[key.ID] = key
	}
	resolver, err := resolverFor(vectors.Keys)
	if err != nil {
		return append(failures, err.Error())
	}

	for _, testCase := range vectors.Sign {
		key, found := byID[testCase.SignerKeyID]
		if !found {
			failures = append(failures, fmt.Sprintf("sign/%s: vector names an unknown key %q", testCase.Name, testCase.SignerKeyID))
			continue
		}
		signer, err := fixture.NewSigner(fixture.Key{ID: key.ID, PrivateHex: key.PrivateHex, PublicHex: key.PublicHex})
		if err != nil {
			failures = append(failures, fmt.Sprintf("sign/%s: %v", testCase.Name, err))
			continue
		}
		compact, err := kernel.Sign([]byte(testCase.Payload), signer)
		if err != nil {
			failures = append(failures, fmt.Sprintf("sign/%s: %v", testCase.Name, err))
			continue
		}
		if compact != testCase.Compact {
			failures = append(failures, fmt.Sprintf("sign/%s: got %s, want %s", testCase.Name, compact, testCase.Compact))
			continue
		}
		if signed := payloadOf(compact); signed != testCase.SignedPayload {
			failures = append(failures, fmt.Sprintf("sign/%s: signed payload is %s, want %s", testCase.Name, signed, testCase.SignedPayload))
		}
	}

	for _, testCase := range vectors.Verify {
		verdict := kernel.Verify(testCase.Compact, resolver)
		if verdict.Valid != testCase.Valid {
			failures = append(failures, fmt.Sprintf("verify/%s: got valid=%t, want valid=%t", testCase.Name, verdict.Valid, testCase.Valid))
			continue
		}
		if testCase.Valid && verdict.KeyID != testCase.KeyID {
			failures = append(failures, fmt.Sprintf("verify/%s: got key %q, want %q", testCase.Name, verdict.KeyID, testCase.KeyID))
		}
	}
	return failures
}

func resolverFor(keys []VectorKey) (fixture.Resolver, error) {
	converted := make([]fixture.Key, 0, len(keys))
	for _, key := range keys {
		converted = append(converted, fixture.Key{ID: key.ID, PrivateHex: key.PrivateHex, PublicHex: key.PublicHex})
	}
	return fixture.NewResolver(converted...)
}

// payloadOf decodes the payload segment of a compact serialization.
func payloadOf(compact string) string {
	parts := strings.Split(compact, ".")
	if len(parts) != 3 {
		return ""
	}
	decoded, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return ""
	}
	return string(decoded)
}
