// The differential harness.
//
// Runs every named implementation over the committed corpus and over
// freshly generated random input, and compares the responses byte for
// byte. Any divergence is a failure in one of them and a finding either
// way; contract/CONTRACT.md is the referee, and this program does not
// decide which side is wrong. It reports the request, the outputs, and
// the seed that produced it, and exits with the divergence code below.
//
// It holds no opinion about what a correct answer is. That is the point:
// golden vectors cannot do this job, because the vectors are generated by
// the implementation they test, so a contract misreading baked into the
// generator produces vectors that agree with the bug. Two implementations
// agreeing is evidence exactly to the extent that they were written
// independently.
//
// Usage:
//   node reference/harness/differential.ts \
//     --impl reference="node reference/adapter.ts" \
//     --impl kernel="cd core && go run ./cmd/kernel-adapter" \
//     [--fresh 2000] [--seed 1] [--corpus reference/corpus]
//
// At least two implementations are required.
//
// Exit codes, and the difference between them is load-bearing:
//
//   0  every implementation returned identical bytes for every request
//   2  a divergence was found, which is the outcome differential-red
//      requires of a planted bug
//   1  the harness could not run: bad arguments, a malformed corpus, an
//      adapter that died or answered the wrong number of requests
//
// A caller that scores any non-zero exit as "the bug was caught" cannot
// tell a working red path from a deleted mutant file, so 2 is separate
// from 1 and the Makefile asserts on it exactly.

import { spawn } from "node:child_process";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { createInterface } from "node:readline";
import { encodeLine, type Request, type Response } from "../adapter.ts";
import { prng, randomRequest } from "./generate.ts";

type Implementation = { name: string; command: string };

type LabelledRequest = { origin: string; request: Request };

/** How many divergences are printed in full before only the count is. */
const REPORTED = 5;

/** A divergence was found. Distinct from 1, which is the harness failing. */
const EXIT_DIVERGENCE = 2;

/**
 * The shape every op requires. A corpus entry is committed once and read
 * forever, so a misspelled op or a missing field is the worst kind of
 * defect here: both implementations reject it for the same uninteresting
 * reason, the entry agrees with itself forever, and the coverage it was
 * added to provide silently is not there. Refusing the run is the only
 * outcome that surfaces it.
 */
const REQUIRED_FIELDS: Record<string, readonly [string, "json" | "string"][]> =
  {
    canonicalize: [["value", "json"]],
    sign: [
      ["payload", "json"],
      ["seedHex", "string"],
    ],
    verify: [
      ["envelope", "string"],
      ["publicKeyHex", "string"],
    ],
    publicKey: [["seedHex", "string"]],
  };

const CRASH_MARKERS = [
  /\bpanic\b/i,
  /\bgoroutine\b/i,
  /runtime error/i,
  /stack overflow/i,
  /maximum call stack/i,
  /index out of range/i,
  /nil pointer/i,
  /invalid memory address/i,
  /\bEPIPE\b/,
  /\bECONNRESET\b/,
];

const options = parseArgv(process.argv.slice(2));

if (options.implementations.length < 2) {
  console.error(
    `FAIL differential: ${options.implementations.length} implementation(s) named; a differential run needs two.`,
  );
  console.error(
    '  The kernel is the usual second: --impl kernel="cd core && go run ./cmd/kernel-adapter".',
  );
  process.exit(1);
}

const requests: LabelledRequest[] = [
  ...corpusRequests(options.corpus),
  ...freshRequests(options.seed, options.fresh),
];

console.log(
  `differential: ${requests.length} requests (${requests.length - options.fresh} corpus, ${options.fresh} fresh at seed ${options.seed}) across ${options.implementations.map((i) => i.name).join(", ")}`,
);

const results = await Promise.all(
  options.implementations.map((implementation) =>
    run(
      implementation,
      requests.map((entry) => entry.request),
    ),
  ),
);

const divergences = compare(options.implementations, requests, results);

if (divergences > 0) {
  console.error(
    `FAIL differential: ${divergences} divergence(s) over ${requests.length} requests. Replay the fresh half with --seed ${options.seed} --fresh ${options.fresh}.`,
  );
  process.exit(EXIT_DIVERGENCE);
}

console.log(
  `differential: zero divergence over ${requests.length} requests across ${options.implementations.length} implementations`,
);

function compare(
  implementations: Implementation[],
  labelled: LabelledRequest[],
  responses: Response[][],
): number {
  const first = implementations[0] as Implementation;
  let divergences = 0;
  for (let index = 0; index < labelled.length; index += 1) {
    const baseline = responses[0]?.[index];
    if (baseline === undefined) {
      throw new Error(`${first.name} returned no response at index ${index}`);
    }
    for (let other = 1; other < implementations.length; other += 1) {
      const candidate = responses[other]?.[index];
      const name = (implementations[other] as Implementation).name;
      if (candidate === undefined) {
        throw new Error(`${name} returned no response at index ${index}`);
      }
      if (identical(baseline, candidate)) continue;
      divergences += 1;
      // A misread rule diverges on a large fraction of the corpus, and a
      // thousand reports of one bug bury the second bug. The first few
      // are what a reader acts on; the count is what tells them how bad
      // it is.
      if (divergences > REPORTED) continue;
      const entry = labelled[index] as LabelledRequest;
      console.error(`DIVERGENCE at ${entry.origin} (request ${index})`);
      console.error(`  request  ${encodeLine(entry.request).trimEnd()}`);
      console.error(`  ${first.name}  ${describe(baseline)}`);
      console.error(`  ${name}  ${describe(candidate)}`);
    }
  }
  return divergences;
}

// `error` is deliberately not compared. Implementations must agree on
// whether an input is rejected, never on how they word it; comparing
// messages would report a divergence on every wording difference and
// train readers to ignore the output.
//
// Two failures are agreement only when both are refusals. A crash on
// either side is a divergence even when the other side also failed,
// because "both broke" is not "both read the contract the same way", and
// scoring it as a match is how a fuzzer reports green while both
// implementations are falling over on the same input.
function identical(a: Response, b: Response): boolean {
  if (a.ok !== b.ok) return false;
  if (a.ok && b.ok) return a.out === b.out;
  if (a.ok || b.ok) return false;
  return refused(a) && refused(b);
}

/**
 * Whether a failed response is a deliberate rejection.
 *
 * An adapter that sets `refused` is taken at its word; this model does,
 * from `respond` in adapter.ts. An adapter that omits it, which is any
 * implementation whose source the harness does not control, is read by
 * the CRASH_MARKERS list. The heuristic errs toward calling something a
 * crash: a refusal misread as a crash is a false divergence somebody
 * investigates and corrects in one line, and a crash misread as a
 * refusal is the silence this whole function exists to prevent.
 */
function refused(response: { refused?: boolean; error: string }): boolean {
  if (typeof response.refused === "boolean") return response.refused;
  return !CRASH_MARKERS.some((marker) => marker.test(response.error));
}

function describe(response: Response): string {
  if (!response.ok) {
    return `${refused(response) ? "refused" : "CRASHED"} (${response.error})`;
  }
  const text = Buffer.from(response.out, "hex").toString("utf8");
  return `${response.out}  ${JSON.stringify(text)}`;
}

/** One adapter subprocess, fed every request, drained in order. */
function run(
  implementation: Implementation,
  requests: Request[],
): Promise<Response[]> {
  return new Promise((resolve, reject) => {
    // stderr is inherited so an adapter that crashes says so in the
    // run output instead of dying silently.
    const child = spawn(implementation.command, {
      shell: true,
      stdio: ["pipe", "pipe", "inherit"],
    });
    const responses: Response[] = [];
    const lines = createInterface({ input: child.stdout });
    lines.on("line", (line) => {
      if (line.trim() === "") return;
      try {
        responses.push(JSON.parse(line) as Response);
      } catch (cause) {
        reject(
          new Error(`${implementation.name} wrote unreadable output: ${line}`, {
            cause,
          }),
        );
      }
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code !== 0) {
        reject(new Error(`${implementation.name} exited ${String(code)}`));
        return;
      }
      if (responses.length !== requests.length) {
        reject(
          new Error(
            `${implementation.name} answered ${responses.length} of ${requests.length} requests`,
          ),
        );
        return;
      }
      resolve(responses);
    });
    for (const request of requests) {
      child.stdin.write(encodeLine(request));
    }
    child.stdin.end();
  });
}

/**
 * The committed corpus: every input a divergence was once found on, plus
 * the terrain the contract argues about. A divergence found once is a
 * regression test forever, which is the whole reason the corpus is in the
 * repository rather than generated fresh each run.
 */
function corpusRequests(directory: string): LabelledRequest[] {
  const entries: LabelledRequest[] = [];
  for (const file of readdirSync(directory).sort()) {
    if (!file.endsWith(".json")) continue;
    const parsed: unknown = JSON.parse(
      readFileSync(join(directory, file), "utf8"),
    );
    if (!Array.isArray(parsed)) {
      throw new Error(`${file}: a corpus file is an array of requests`);
    }
    parsed.forEach((request, index) => {
      entries.push({
        origin: `${file}[${index}]`,
        request: validated(request, `${file}[${index}]`),
      });
    });
  }
  if (entries.length === 0) {
    throw new Error(`${directory}: the corpus is empty`);
  }
  return entries;
}

function validated(entry: unknown, origin: string): Request {
  if (entry === null || typeof entry !== "object" || Array.isArray(entry)) {
    throw new Error(`${origin}: a corpus entry is an object`);
  }
  const record = entry as Record<string, unknown>;
  const op = record["op"];
  if (typeof op !== "string" || !(op in REQUIRED_FIELDS)) {
    throw new Error(
      `${origin}: op ${JSON.stringify(op)} is not one of ${Object.keys(REQUIRED_FIELDS).sort().join(", ")}`,
    );
  }
  const fields = REQUIRED_FIELDS[op] as readonly [string, "json" | "string"][];
  for (const [field, kind] of fields) {
    if (!(field in record)) {
      throw new Error(`${origin}: op ${op} requires the field ${field}`);
    }
    if (kind === "string" && typeof record[field] !== "string") {
      throw new Error(`${origin}: ${field} must be a string`);
    }
  }
  const allowed = new Set(["op", ...fields.map(([field]) => field)]);
  for (const field of Object.keys(record)) {
    if (!allowed.has(field)) {
      throw new Error(`${origin}: op ${op} has no field ${field}`);
    }
  }
  return record as unknown as Request;
}

function freshRequests(seed: number, count: number): LabelledRequest[] {
  const random = prng(seed);
  const entries: LabelledRequest[] = [];
  for (let index = 0; index < count; index += 1) {
    entries.push({
      origin: `fresh(seed ${seed})[${index}]`,
      request: randomRequest(random),
    });
  }
  return entries;
}

function parseArgv(argv: string[]): {
  implementations: Implementation[];
  fresh: number;
  seed: number;
  corpus: string;
} {
  const implementations: Implementation[] = [];
  let fresh = 2000;
  // A run with no seed given picks one and prints it, so an intermittent
  // divergence is replayable from the failure output rather than lost.
  let seed = Math.floor(Math.random() * 2 ** 31);
  let corpus = "reference/corpus";
  for (let index = 0; index < argv.length; index += 1) {
    const flag = argv[index];
    const value = argv[index + 1];
    if (value === undefined) throw new Error(`${String(flag)} needs a value`);
    index += 1;
    switch (flag) {
      case "--impl": {
        const at = value.indexOf("=");
        if (at < 1) throw new Error(`--impl takes name=command, got ${value}`);
        implementations.push({
          name: value.slice(0, at),
          command: value.slice(at + 1),
        });
        break;
      }
      case "--fresh":
        fresh = count(flag, value, 0);
        break;
      case "--seed":
        seed = count(flag, value, 0);
        break;
      case "--corpus":
        corpus = value;
        break;
      default:
        throw new Error(`unknown flag ${String(flag)}`);
    }
  }
  return { implementations, fresh, seed, corpus };
}

/**
 * A non-negative integer, or the run refuses to start.
 *
 * Bare `Number()` is what makes a typo silent here: `--fresh 20O00`, with
 * a letter O, is NaN, and NaN requests generated is a loop that runs zero
 * times. The run then compares the corpus alone, prints "NaN fresh", and
 * exits 0 green while the twenty thousand generated cases it was asked
 * for never existed. A fuzzer that can be switched off by a typo is worse
 * than no fuzzer, because it still reports success.
 */
function count(flag: string, value: string, minimum: number): number {
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed < minimum) {
    throw new Error(
      `${flag} takes an integer of at least ${minimum}, got ${JSON.stringify(value)}`,
    );
  }
  return parsed;
}
