// The differential harness.
//
// Runs every named implementation over the committed corpus and over
// freshly generated random input, and compares the responses byte for
// byte. Any divergence is a failure in one of them and a finding either
// way; contract/CONTRACT.md is the referee, and this program does not
// decide which side is wrong. It reports the request, the outputs, and
// the seed that produced it, and exits 1.
//
// It holds no opinion about what a correct answer is. That is the point:
// golden vectors cannot do this job, because the vectors are generated by
// the implementation they test, so a contract misreading baked into the
// generator produces vectors that agree with the bug. Two implementations
// agreeing is evidence exactly to the extent that they were written
// independently.
//
// Usage:
//   node reference/harness/differential.ts \
//     --impl reference="node reference/adapter.ts" \
//     --impl kernel="./core/bin/kernel-adapter" \
//     [--fresh 2000] [--seed 1] [--corpus reference/corpus]
//
// At least two implementations are required. Exit 0 means every
// implementation returned identical bytes for every request.

import { spawn } from "node:child_process";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { createInterface } from "node:readline";
import { encodeLine, type Request, type Response } from "../adapter.ts";
import { prng, randomRequest } from "./generate.ts";

type Implementation = { name: string; command: string };

type LabelledRequest = { origin: string; request: Request };

/** How many divergences are printed in full before only the count is. */
const REPORTED = 5;

const options = parseArgv(process.argv.slice(2));

if (options.implementations.length < 2) {
  console.error(
    `FAIL differential: ${options.implementations.length} implementation(s) named; a differential run needs two.`,
  );
  console.error(
    "  The kernel adapter is the second one. Until trust-kernel/01 lands there is nothing to differ from.",
  );
  process.exit(1);
}

const requests: LabelledRequest[] = [
  ...corpusRequests(options.corpus),
  ...freshRequests(options.seed, options.fresh),
];

console.log(
  `differential: ${requests.length} requests (${requests.length - options.fresh} corpus, ${options.fresh} fresh at seed ${options.seed}) across ${options.implementations.map((i) => i.name).join(", ")}`,
);

const results = await Promise.all(
  options.implementations.map((implementation) =>
    run(
      implementation,
      requests.map((entry) => entry.request),
    ),
  ),
);

const divergences = compare(options.implementations, requests, results);

if (divergences > 0) {
  console.error(
    `FAIL differential: ${divergences} divergence(s) over ${requests.length} requests. Replay the fresh half with --seed ${options.seed} --fresh ${options.fresh}.`,
  );
  process.exit(1);
}

console.log(
  `differential: zero divergence over ${requests.length} requests across ${options.implementations.length} implementations`,
);

function compare(
  implementations: Implementation[],
  labelled: LabelledRequest[],
  responses: Response[][],
): number {
  const first = implementations[0] as Implementation;
  let divergences = 0;
  for (let index = 0; index < labelled.length; index += 1) {
    const baseline = responses[0]?.[index];
    if (baseline === undefined) {
      throw new Error(`${first.name} returned no response at index ${index}`);
    }
    for (let other = 1; other < implementations.length; other += 1) {
      const candidate = responses[other]?.[index];
      const name = (implementations[other] as Implementation).name;
      if (candidate === undefined) {
        throw new Error(`${name} returned no response at index ${index}`);
      }
      if (identical(baseline, candidate)) continue;
      divergences += 1;
      // A misread rule diverges on a large fraction of the corpus, and a
      // thousand reports of one bug bury the second bug. The first few
      // are what a reader acts on; the count is what tells them how bad
      // it is.
      if (divergences > REPORTED) continue;
      const entry = labelled[index] as LabelledRequest;
      console.error(`DIVERGENCE at ${entry.origin} (request ${index})`);
      console.error(`  request  ${encodeLine(entry.request).trimEnd()}`);
      console.error(`  ${first.name}  ${describe(baseline)}`);
      console.error(`  ${name}  ${describe(candidate)}`);
    }
  }
  return divergences;
}

// `error` is deliberately not compared. Implementations must agree on
// whether an input is rejected, never on how they word it; comparing
// messages would report a divergence on every wording difference and
// train readers to ignore the output.
function identical(a: Response, b: Response): boolean {
  if (a.ok !== b.ok) return false;
  return !a.ok || !b.ok || a.out === b.out;
}

function describe(response: Response): string {
  if (!response.ok) return `rejected (${response.error})`;
  const text = Buffer.from(response.out, "hex").toString("utf8");
  return `${response.out}  ${JSON.stringify(text)}`;
}

/** One adapter subprocess, fed every request, drained in order. */
function run(
  implementation: Implementation,
  requests: Request[],
): Promise<Response[]> {
  return new Promise((resolve, reject) => {
    // stderr is inherited so an adapter that crashes says so in the
    // run output instead of dying silently.
    const child = spawn(implementation.command, {
      shell: true,
      stdio: ["pipe", "pipe", "inherit"],
    });
    const responses: Response[] = [];
    const lines = createInterface({ input: child.stdout });
    lines.on("line", (line) => {
      if (line.trim() === "") return;
      try {
        responses.push(JSON.parse(line) as Response);
      } catch (cause) {
        reject(
          new Error(`${implementation.name} wrote unreadable output: ${line}`, {
            cause,
          }),
        );
      }
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code !== 0) {
        reject(new Error(`${implementation.name} exited ${String(code)}`));
        return;
      }
      if (responses.length !== requests.length) {
        reject(
          new Error(
            `${implementation.name} answered ${responses.length} of ${requests.length} requests`,
          ),
        );
        return;
      }
      resolve(responses);
    });
    for (const request of requests) {
      child.stdin.write(encodeLine(request));
    }
    child.stdin.end();
  });
}

/**
 * The committed corpus: every input a divergence was once found on, plus
 * the terrain the contract argues about. A divergence found once is a
 * regression test forever, which is the whole reason the corpus is in the
 * repository rather than generated fresh each run.
 */
function corpusRequests(directory: string): LabelledRequest[] {
  const entries: LabelledRequest[] = [];
  for (const file of readdirSync(directory).sort()) {
    if (!file.endsWith(".json")) continue;
    const parsed: unknown = JSON.parse(
      readFileSync(join(directory, file), "utf8"),
    );
    if (!Array.isArray(parsed)) {
      throw new Error(`${file}: a corpus file is an array of requests`);
    }
    parsed.forEach((request, index) => {
      entries.push({
        origin: `${file}[${index}]`,
        request: request as Request,
      });
    });
  }
  return entries;
}

function freshRequests(seed: number, count: number): LabelledRequest[] {
  const random = prng(seed);
  const entries: LabelledRequest[] = [];
  for (let index = 0; index < count; index += 1) {
    entries.push({
      origin: `fresh(seed ${seed})[${index}]`,
      request: randomRequest(random),
    });
  }
  return entries;
}

function parseArgv(argv: string[]): {
  implementations: Implementation[];
  fresh: number;
  seed: number;
  corpus: string;
} {
  const implementations: Implementation[] = [];
  let fresh = 2000;
  // A run with no seed given picks one and prints it, so an intermittent
  // divergence is replayable from the failure output rather than lost.
  let seed = Math.floor(Math.random() * 2 ** 31);
  let corpus = "reference/corpus";
  for (let index = 0; index < argv.length; index += 1) {
    const flag = argv[index];
    const value = argv[index + 1];
    if (value === undefined) throw new Error(`${String(flag)} needs a value`);
    index += 1;
    switch (flag) {
      case "--impl": {
        const at = value.indexOf("=");
        if (at < 1) throw new Error(`--impl takes name=command, got ${value}`);
        implementations.push({
          name: value.slice(0, at),
          command: value.slice(at + 1),
        });
        break;
      }
      case "--fresh":
        fresh = Number(value);
        break;
      case "--seed":
        seed = Number(value);
        break;
      case "--corpus":
        corpus = value;
        break;
      default:
        throw new Error(`unknown flag ${String(flag)}`);
    }
  }
  return { implementations, fresh, seed, corpus };
}
