// The spike's imprint payload, read from the committed fixture.
//
// The fixture is generated by `pnpm run fixture` from `imprint/imprint.py`,
// the canonical generator, so the geometry the renderer is asked to carry is
// the geometry the product actually produces. Nothing here recomputes it: a
// second implementation of the figure is the thing not to build.

import fixture from "../fixtures/imprint-worst-case.json";

export type ImprintFixture = {
  /** The reference record the figure was drawn from, by its name in `imprint/examples.py`. */
  case: string;
  /** CSS pixels the figure was drawn for, and the device pixel ratio it was budgeted at. */
  size: number;
  dpr: number;
  viewBox: number;
  ink: string;
  paper: string;
  strokePx: number;
  /** Path commands across every thread. The load this spike puts on the renderer. */
  vertices: number;
  paths: string[];
};

export const imprintFixture: ImprintFixture = fixture as ImprintFixture;
