// The reference model against the values contract/CONTRACT.md states
// literally.
//
// Every expectation below is written in the contract as text, not read
// off a run of this code. That is the whole distinction from a golden
// vector: a vector generated by the implementation it tests agrees with
// whatever bug the generator had, and the contract's own sentences do
// not. The cases the contract does not spell out are the differential
// harness's job, not this file's.
//
// Usage: node reference/conformance.test.ts

import {
  CONTRACT_RULES,
  canonicalizeToString,
  compareCodeUnits,
} from "./canonical.ts";
import {
  PROTECTED_HEADER,
  canonicalVerdict,
  publicHexFromSeedHex,
  signEnvelope,
  verifyEnvelope,
} from "./jws.ts";
import { EDGE_STRINGS } from "./harness/generate.ts";

let assertions = 0;
const text = (bytes: Uint8Array) => Buffer.from(bytes).toString("utf8");

// Rule 2, its four named number cases.
equal(canonicalizeToString(-0), "0", "rule 2: -0 formats as 0");
equal(canonicalizeToString(0), "0", "rule 2: 0 formats as 0");
equal(canonicalizeToString(1e21), "1e+21", "rule 2: 1e21 carries a + sign");
equal(canonicalizeToString(-1e21), "-1e+21", "rule 2: so does -1e21");
equal(
  canonicalizeToString(1e20),
  "100000000000000000000",
  "rule 2: 1e20 is below the exponent threshold and stays full-decimal",
);
equal(canonicalizeToString(1e-7), "1e-7", "rule 2: 1e-7 is exponential");
equal(
  canonicalizeToString(0.000001),
  "0.000001",
  "rule 2: 0.000001 is the last fixed-point step above it",
);
equal(
  canonicalizeToString(2 ** 53 - 1),
  "9007199254740991",
  "rule 2: integers up to 2^53-1 are full-decimal",
);

// Rule 2's key order. UTF-16 code units and UTF-8 bytes disagree here and
// nowhere in the BMP, so this pair is the whole content of the rule.
const emoji = "\u{1f600}"; // U+1F600
const fullwidthZ = "\uff3a"; // U+FF3A
assert(
  compareCodeUnits(emoji, fullwidthZ) < 0,
  "rule 2: U+1F600 sorts below U+FF3A by UTF-16 code unit",
);
assert(
  Buffer.compare(Buffer.from(emoji), Buffer.from(fullwidthZ)) > 0,
  "rule 2: and above it by UTF-8 byte, which is the order the rule rejects",
);
equal(
  canonicalizeToString({ [fullwidthZ]: 2, [emoji]: 1 }),
  `{"${emoji}":1,"${fullwidthZ}":2}`,
  "rule 2: the emitted key order is the UTF-16 one",
);

// Rule 1: normalization NONE. NFC and NFD are two strings and two keys.
const nfc: string = "\u00e9"; // NFC e-acute
const nfd: string = "\u0065\u0301"; // NFD e-acute
assert(nfc !== nfd, "rule 1: the two spellings are distinct strings");
equal(
  canonicalizeToString({ [nfc]: 1, [nfd]: 2 }),
  `{"${nfd}":2,"${nfc}":1}`,
  "rule 1: both keys survive, in UTF-16 order",
);
equal(
  CONTRACT_RULES.normalizeString(nfd),
  nfd,
  "rule 1: the contract reading normalizes nothing",
);

// Rule 1's escaping, via JCS. The cases a JSON serializer gets wrong.
equal(canonicalizeToString("/"), '"/"', "JCS leaves the solidus unescaped");
equal(
  canonicalizeToString("\u007f"),
  '"\u007f"',
  "JCS leaves DEL literal, unlike several JSON libraries",
);
equal(
  canonicalizeToString("\u0000\u001f"),
  '"\\u0000\\u001f"',
  "C0 outside the short forms escapes as lowercase \\u00xx",
);
equal(
  canonicalizeToString('\b\t\n\f\r"\\'),
  '"\\b\\t\\n\\f\\r\\"\\\\"',
  "the seven short forms",
);
equal(
  canonicalizeToString({ a: [], b: {} }),
  '{"a":[],"b":{}}',
  "no whitespace anywhere",
);

// Rule 3: the protected header is 15 bytes and is compared as bytes.
equal(PROTECTED_HEADER.length, 15, "rule 3: the header is 15 bytes");
equal(text(PROTECTED_HEADER), '{"alg":"EdDSA"}', "rule 3: and these bytes");

// Rule 4: RFC 8032 test vectors 1 and 2, seed hex in, raw public hex out.
equal(
  publicHexFromSeedHex(
    "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60",
  ),
  "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a",
  "rule 4: RFC 8032 vector 1",
);
equal(
  publicHexFromSeedHex(
    "4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb",
  ),
  "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c",
  "rule 4: RFC 8032 vector 2",
);

// Rule 3: compact serialization, and the verdict shapes.
const seed = "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60";
const publicHex = publicHexFromSeedHex(seed);
const envelope = signEnvelope({ kid: "operator-1", claim: "x" }, seed);
const [header, payload, signature] = envelope.split(".") as [
  string,
  string,
  string,
];
equal(envelope.split(".").length, 3, "rule 3: three compact segments");
equal(
  header,
  "eyJhbGciOiJFZERTQSJ9",
  "rule 3: the header segment is the 15 bytes, base64url, unpadded",
);
assert(
  !envelope.includes("="),
  "rule 3: base64url in a compact serialization carries no padding",
);
equal(
  JSON.stringify(verifyEnvelope(envelope, publicHex)),
  '{"valid":true}',
  "a good envelope verifies",
);
equal(
  text(
    canonicalVerdict(
      `${header}.${payload}.${signature.slice(0, -1)}A`,
      publicHex,
    ),
  ),
  '{"valid":false}',
  "rule 3: a false verdict is exactly this, with no extra fields",
);
equal(
  text(canonicalVerdict(envelope, publicHexFromSeedHex("0".repeat(64)))),
  '{"valid":false}',
  "the wrong key is a false verdict and nothing more",
);

// Rule 3's reason for freezing the header: a header that parses to the
// same JSON, or to a superset of it, is still not those 15 bytes.
for (const spelling of [
  '{"alg":"EdDSA" }',
  '{ "alg":"EdDSA"}',
  '{"alg":"EdDSA","kid":"operator-1"}',
  '{"kid":"operator-1","alg":"EdDSA"}',
  '{"alg":"none"}',
]) {
  const segment = Buffer.from(spelling).toString("base64url");
  equal(
    JSON.stringify(
      verifyEnvelope(`${segment}.${payload}.${signature}`, publicHex),
    ),
    '{"valid":false}',
    `rule 3: header ${spelling} is not the frozen 15 bytes`,
  );
}

// Rule 3: verification does not re-canonicalize the payload. A payload
// segment that decodes to the same JSON value but different bytes must
// fail, because the signature was over the bytes.
const reordered = Buffer.from('{"kid":"operator-1","claim":"x"}').toString(
  "base64url",
);
assert(
  reordered !== payload,
  "the reordered payload really is different bytes",
);
equal(
  JSON.stringify(
    verifyEnvelope(`${header}.${reordered}.${signature}`, publicHex),
  ),
  '{"valid":false}',
  "rule 3: an equivalent payload with different bytes does not verify",
);

// Rule 1, decision 082: a document containing an unpaired surrogate is
// refused, never altered and never escaped. The refusal is what is
// asserted, and so is the absence of the two behaviours ruled against:
// substituted output and escaped output would both be a returned value.
const HIGH = "\ud800";
const LOW = "\udfff";
for (const [what, value] of [
  ["a lone high surrogate", HIGH],
  ["a lone low surrogate", LOW],
  ["a surrogate inside a longer string", `a${HIGH}b`],
  ["two highs in a row", `${HIGH}${HIGH}`],
  ["a reversed pair", `${LOW}${HIGH}`],
  ["a surrogate in a key", { [HIGH]: 1 }],
  ["a surrogate nested in an array", { ok: [HIGH] }],
  ["a surrogate several levels down", { a: { b: [1, { c: LOW }] } }],
] as [string, Parameters<typeof canonicalizeToString>[0]][]) {
  refuses(() => canonicalizeToString(value), `rule 1 refuses ${what}`);
}
refuses(
  () => signEnvelope({ kid: "operator-1", bad: HIGH }, seed),
  "rule 1's refusal reaches signing, which canonicalizes first",
);

// The other half: refusal must not have become refuse-everything. A
// well-formed pair spelling the same code points is accepted, and its
// output is the character, not an escape.
equal(
  canonicalizeToString("\ud83d\ude00"),
  '"\ud83d\ude00"',
  "a well-formed surrogate pair is accepted and emitted literally",
);
equal(
  canonicalizeToString({ "\udbff\udfff": 1 }),
  '{"\udbff\udfff":1}',
  "so is the last code point, whose halves are both surrogates",
);

// Rule 3, decision 082: every base64url segment must be the canonical
// spelling of its bytes, padding and slack final-character bits alike.
for (const [what, bad] of [
  ["padding on the header", `${header}=.${payload}.${signature}`],
  ["padding on the payload", `${header}.${payload}=.${signature}`],
  ["padding on the signature", `${header}.${payload}.${signature}=`],
] as [string, string][]) {
  equal(
    JSON.stringify(verifyEnvelope(bad, publicHex)),
    '{"valid":false}',
    `rule 3 rejects ${what}`,
  );
}
{
  // A 64-byte signature is 86 base64url characters, and the last one
  // carries four slack bits. A spelling that sets them decodes to the
  // same bytes and is still not the canonical spelling.
  const alphabet =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
  const bytes = Buffer.from(signature, "base64url");
  const slack = [...alphabet]
    .map((character) => `${signature.slice(0, -1)}${character}`)
    .find(
      (candidate) =>
        candidate !== signature &&
        Buffer.from(candidate, "base64url").equals(bytes),
    ) as string;
  assert(
    slack !== undefined && Buffer.from(slack, "base64url").length === 64,
    "a slack-bit spelling of the signature exists and decodes to the same 64 bytes",
  );
  equal(
    JSON.stringify(verifyEnvelope(`${header}.${payload}.${slack}`, publicHex)),
    '{"valid":false}',
    "rule 3 rejects a signature segment whose final character has slack bits set",
  );
}

// A generator guard, not a contract rule. The NFC and NFD entries in
// EDGE_STRINGS are indistinguishable on screen, so an editor or a tool
// that normalizes the file would collapse them and silently delete the
// only inputs that test rule 1. This assertion is how that gets noticed.
equal(
  new Set(EDGE_STRINGS).size,
  EDGE_STRINGS.length,
  "the generator's edge strings are pairwise distinct",
);

console.log(`\nconformance: ${assertions} assertions passed`);

function equal(actual: unknown, expected: unknown, what: string): void {
  assert(
    Object.is(actual, expected),
    `${what}\n    expected ${JSON.stringify(expected)}\n    actual   ${JSON.stringify(actual)}`,
  );
}

/** Asserts that a call refuses, which under decision 082 means throwing. */
function refuses(call: () => unknown, what: string): void {
  let returned: unknown;
  try {
    returned = call();
  } catch {
    assertions += 1;
    return;
  }
  console.error(
    `FAIL ${what}\n    it returned ${JSON.stringify(returned)} instead of refusing`,
  );
  process.exit(1);
}

function assert(condition: boolean, what: string): void {
  if (!condition) {
    console.error(`FAIL ${what}`);
    process.exit(1);
  }
  assertions += 1;
}
