// Type generation from both live schemas (foundation/02). Reads every
// base table in each plane's database and emits row types into Go and TS,
// namespaced by plane — one Go package and one TS module per database,
// no shared namespace. The TS types carry a per-plane unique-symbol brand
// because TS typing is structural: without the brand, two identically
// shaped rows would be interchangeable across planes, which is exactly
// the reuse the plane split forbids. Go types are nominal already —
// distinct named types in distinct packages do not assign.
//
// `--check` regenerates in memory and diffs against the committed output;
// any difference exits 1, which is how CI fails a table edited without
// regenerated types.
//
// Usage: node db/typegen.mjs [--check]
// Requires both databases up and migrated (`make db-up && make migrate`).
// Dependency-free: introspection goes through `docker compose exec psql`.

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

const PLANES = ["spine", "payload"];
const CHECK = process.argv.includes("--check");

// Postgres type -> [Go type, TS type]. Extended deliberately, one entry
// per justified type; an unknown type fails loudly rather than guessing.
const TYPE_MAP = new Map([
  ["integer", ["int32", "number"]],
  ["bigint", ["int64", "string"]],
  ["text", ["string", "string"]],
  ["boolean", ["bool", "boolean"]],
  ["bytea", ["[]byte", "Uint8Array"]],
  ["timestamp with time zone", ["time.Time", "string"]],
  // uuid: introduced by 0005-dek-registry's person_id (foundation/05)
  // and used by 0020-cross-plane-outbox's entry ids (foundation/07).
  // Ledger ids travel as their canonical lowercase string form in both
  // languages; nothing computes on the bits.
  ["uuid", ["string", "string"]],
]);

const failures = [];
for (const plane of PLANES) {
  const tables = introspect(plane);
  emit(`core/gen/${plane}/${plane}.go`, goSource(plane, tables));
  emit(`db/gen/${plane}.ts`, tsSource(plane, tables));
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`FAIL ${failure}`);
  process.exit(1);
}
console.log(
  CHECK
    ? "typegen: committed types match both live schemas"
    : "typegen: generated types for both planes",
);

function introspect(plane) {
  const rows = psql(
    plane,
    `SELECT c.table_name, c.column_name, c.data_type, c.is_nullable
       FROM information_schema.columns c
       JOIN information_schema.tables t
         ON t.table_schema = c.table_schema AND t.table_name = c.table_name
      WHERE c.table_schema = 'public' AND t.table_type = 'BASE TABLE'
      ORDER BY c.table_name, c.ordinal_position`,
  );
  const tables = new Map();
  for (const line of rows) {
    const [table, column, dataType, isNullable] = line.split("\t");
    if (!TYPE_MAP.has(dataType)) {
      console.error(
        `typegen: ${plane}.${table}.${column} has type "${dataType}" with no mapping in db/typegen.mjs — add one deliberately`,
      );
      process.exit(1);
    }
    if (!tables.has(table)) tables.set(table, []);
    tables
      .get(table)
      .push({ column, dataType, nullable: isNullable === "YES" });
  }
  return tables;
}

function goSource(plane, tables) {
  const needsTime = [...tables.values()].some((columns) =>
    columns.some((c) => c.dataType === "timestamp with time zone"),
  );
  const lines = [
    `// Code generated by db/typegen.mjs from the live ${plane} schema. DO NOT EDIT.`,
    ``,
    `// Package ${plane} holds row types for the ${plane} plane only. It is`,
    `// generated per database with no shared namespace: a ${other(plane)} type`,
    `// must not satisfy a ${plane}-typed parameter, and does not — the types`,
    `// are distinct named types in distinct packages.`,
    `package ${plane}`,
    ``,
  ];
  if (needsTime) lines.push(`import "time"`, ``);
  for (const [table, columns] of tables) {
    // Field names are padded to one column, matching gofmt's alignment,
    // so the output is gofmt-clean without a Go toolchain at hand.
    const width = Math.max(...columns.map((c) => pascal(c.column).length));
    lines.push(`// ${pascal(table)}Row is one row of ${plane}.${table}.`);
    lines.push(`type ${pascal(table)}Row struct {`);
    for (const { column, dataType, nullable } of columns) {
      const [goType] = TYPE_MAP.get(dataType);
      const field = pascal(column).padEnd(width);
      lines.push(`\t${field} ${nullable ? "*" + goType : goType}`);
    }
    lines.push(`}`, ``);
  }
  return lines.join("\n");
}

function tsSource(plane, tables) {
  const lines = [
    `// Code generated by db/typegen.mjs from the live ${plane} schema. DO NOT EDIT.`,
    ``,
    `// Row types for the ${plane} plane only, generated per database with no`,
    `// shared namespace. The unique-symbol brand makes the types nominal:`,
    `// a ${other(plane)} row cannot satisfy a ${plane}-typed parameter even`,
    `// when the row shapes coincide.`,
    `export declare const ${plane}Plane: unique symbol;`,
    ``,
  ];
  for (const [table, columns] of tables) {
    lines.push(`/** One row of ${plane}.${table}. */`);
    lines.push(`export interface ${pascal(table)}Row {`);
    lines.push(`  readonly [${plane}Plane]: "${plane}";`);
    for (const { column, dataType, nullable } of columns) {
      const [, tsType] = TYPE_MAP.get(dataType);
      lines.push(`  ${column}: ${nullable ? tsType + " | null" : tsType};`);
    }
    lines.push(`}`, ``);
  }
  return lines.join("\n");
}

function emit(path, source) {
  const content = source.endsWith("\n") ? source : `${source}\n`;
  if (CHECK) {
    const committed = existsSync(path) ? readFileSync(path, "utf8") : null;
    if (committed !== content) {
      failures.push(
        `${path} does not match the live schema — run \`make typegen\` and commit the result`,
      );
    }
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.log(`typegen: wrote ${path}`);
}

function pascal(name) {
  return name
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function other(plane) {
  return plane === "spine" ? "payload" : "spine";
}

function psql(plane, query) {
  const out = execFileSync(
    "docker",
    [
      "compose",
      "exec",
      "-T",
      plane,
      "psql",
      "-v",
      "ON_ERROR_STOP=1",
      "-U",
      "identity",
      "-d",
      plane,
      "-tA",
      "-F",
      "\t",
      "-c",
      query,
    ],
    { encoding: "utf8", stdio: ["pipe", "pipe", "inherit"] },
  ).trim();
  return out === "" ? [] : out.split("\n");
}
